steps:
- name: node:20.0.0
  entrypoint: npm
  args: ["install"]
- name: node:20.0.0
  entrypoint: npm
  args: ["run", "create-env"]
  env:
    - 'SECRET_KEY=${_SECRET_KEY}'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "${_CONFIG_FILE}"]
timeout: "1600s"
options:
  logging: CLOUD_LOGGING_ONLY